<?php
/**
 * @file soyoco.module
 * Drupal 7 module
 */

module_load_include('inc','soyoco','soyoco.util');
module_load_include('inc','soyoco','soyoco.compute');
module_load_include('inc','soyoco','soyoco.node');
module_load_include('inc','soyoco','soyoco.query');
module_load_include('inc','soyoco','soyoco.theme');


/**
 * Implements HOOK_nodeapi.
 *
 */
function soyoco_init() {
  if (arg(0) === 'shares') {
    _soyoco_update_shares();
    drupal_set_message('updated shares');
  }

  if (arg(0) === 'shifts' ) {
    _soyoco_update_shifts();
    drupal_set_message('updated shifts');
  }
}


/**
 * Implements HOOK_user_view.
 *
 */
function soyoco_user_view($account, $view_mode = 'full', $langcode = NULL) {
    
  // removing 'member for...' message
  if (!isset($account->content['summary'])) {
    $account->content['summary'] = array();
  }
  if (isset($account->content['summary']['member_for'])) {
    unset($account->content['summary']['member_for']);
  }
  
  // adding more to the user summary  
  $account->content['summary'] += array(
    '#type' => 'user_profile_category', 
    '#attributes' => array('class' => array('user-member')), 
    '#weight' => 5, 
    '#title' => t('My Yogurt Account'),
  );
  
  $account->content['summary']['soyoco'] =  array(
    '#type' => 'user_profile_item',
    '#attributes' => array('class' => array('soyoco')), 
    '#title' =>  t('My Active Share'),
    '#markup' => 
      _soyoco_render_user_page($account->uid), 
      '#attributes' => array('class' => array('icon-heart')
    ),
  );
}


/**
 * Implements HOOK_user_login.
 */
function soyoco_user_login(&$edit, $account) {
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    $_GET['destination'] = 'user';
  }
}


