<?php

/**
 * @file soyoco.module
 * Drupal 7 module
 */

function soyoco_init() {
  module_load_include('inc', 'soyoco', 'soyoco.compute');
  module_load_include('inc', 'soyoco', 'soyoco.util');
}

/**
 * implements hook_nodeapi()
 *
 *
 */
function soyoco_nodeapi() {
 /*
 // @TODO auto-create missing work-shifts
 //
 // when you save a share node,
 // compare it's end date to future-est end date var
 // if it's less-than, do nothing.
 // if it's more than,
 //    loop from futurest end date var to this new end_date
 //        create a new work shift for each week
 */
  switch($type) {
    case 'yogurt_share':
      if ($op === 'view') {
        $node->wjars_val  = soyoco_view_node_fields($node,'w_jars');
        $node->njars_val  = soyoco_view_node_fields($node,'n_jars');
        $node->duration   = soyoco_view_node_fields($node,'begin_date');
        $node->end_date   = $node->field_begin_date['und'][0]['value2'];
        $node->weeks_left = soyoco_weeks_til_expiry($end_date);
      }
      break;
  }
}


/**
 * implements hook_theme()
 *
 *
 */
function soyoco_theme() {
  $tpl_path = drupal_get_path('module', 'soyoco') . '/theme';
  return array(
    'soyoco_user_profile_view' => array(
      'arguments' => array(),
      'template' => 'user-profile-view',
      'path' => $tpl_path,
    ),
  );
}
/**
 * implements hook_user()
 *
 *
 */
function soyoco_user_view($account, $view_mode = 'full', $langcode = NULL) {
  //drupal_set_message(t('Look at me! 2'));
    
  if (!isset($account->content['summary'])) {
    $account->content['summary'] = array();
  }
  if (isset($account->content['summary']['member_for'])) {
    unset($account->content['summary']['member_for']);
  }
    
  $account->content['summary'] += array(
    '#type' => 'user_profile_category', 
    '#attributes' => array('class' => array('user-member')), 
    '#weight' => 5, 
    '#title' => t('My Yogurt Account'),
  );
  
  global $user;
  $query = db_select('node', 'n')
    ->fields('n')
    //->fields('n',array('field_w_jars', 'field_n_jars'))
    ->condition('uid',$user->uid,'=')
    ->orderBy('created', 'DESC');
  
  $result = $query->execute();
  $count = $result->rowCount();
  
  $output = '';
  if ($count < 1) {
    $output .= 'You do not currently have an active share.';
  } else {
    while($record = $result->fetchAssoc()) {
      //$output .= print_r($record,TRUE);
      $node = node_load($record['nid']);
      $wjars_val = soyoco_view_node_fields($node,'w_jars');
      $njars_val = soyoco_view_node_fields($node,'n_jars');
      $duration = soyoco_view_node_fields($node,'begin_date');
      $end_date = $node->field_begin_date['und'][0]['value2'];
      $weeks_left = soyoco_weeks_til_expiry($end_date);
      $output .= soyoco_theme_share($wjars_val,$njars_val,$weeks_left,$duration);
    }
  }
  $account->content['summary']['soyoco'] =  array(
    '#type' => 'user_profile_item',
    '#attributes' => array('class' => array('soyoco')), 
    '#title' =>  t('My Active Share'),
    '#markup' => 
      t($output), 
      '#attributes' => array('class' => array('icon-heart')
    ),
  );
}
