<?php
/**
 * @file soyoco.module
 * Drupal 7 module
 */

module_load_include('inc','soyoco','soyoco.util');
module_load_include('inc','soyoco','soyoco.compute');
module_load_include('inc','soyoco','soyoco.node');
module_load_include('inc','soyoco','soyoco.query');
module_load_include('inc','soyoco','soyoco.theme');
module_load_include('inc','soyoco','soyoco.pages');

/**
 * Implements HOOK_nodeapi.
 *
 */
function soyoco_init() {
  if (arg(0) === 'shares') {
    _soyoco_update_shares();
    drupal_set_message('updated shares');
  }

  if (arg(0) === 'shifts' ) {
    _soyoco_update_shifts();
    drupal_set_message('updated shifts');
  }
}

function soyoco_cron() {
  _soyoco_update_shares();
  _soyoco_update_shifts();
  _soyoco_simple_mail('Cron ran', 'Updated shares and shifts.');
}


/**
 * Sends a simple email.
 *
 */
function _soyoco_simple_mail($message_subject, $message_body) {
  $my_module = 'soyocodddss';
  $my_mail_token = '';
  $from = variable_get('system_mail', 'organization@example.com');
  $message = array(
    'id' => $my_module . '_' . $my_mail_token,
    'to' => 'get.oren@gmail.com',
    'subject' => $message_subject,
    'body' => array($message_body),
    'headers' => array(
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
    ),
  );
  $system = drupal_mail_system($my_module, $my_mail_token);

  // The format function must be called before calling the mail function. 
  $message = $system->format($message);

  if ($system->mail($message)) {
    // Success.
    drupal_set_message('mail SUCCESS');
  }
  else {
    // Failure.
    drupal_set_message('mail FAIL');
  }
}


/**
 * Implements HOOK_user_view.
 *
 */
function soyoco_user_view($account, $view_mode = 'full', $langcode = NULL) {
    
  // removing 'member for...' message
  if (!isset($account->content['summary'])) {
    $account->content['summary'] = array();
  }
  if (isset($account->content['summary']['member_for'])) {
    unset($account->content['summary']['member_for']);
  }
  
  // adding more to the user summary  
  $account->content['summary'] += array(
    '#type' => 'user_profile_category', 
    '#attributes' => array('class' => array('user-member')), 
    '#weight' => 5, 
    '#title' => t('My Yogurt Account'),
  );
  
  $account->content['summary']['soyoco'] =  array(
    '#type' => 'user_profile_item',
    '#attributes' => array('class' => array('soyoco')), 
    '#title' =>  t('My Active Share'),
    '#markup' => 
      _soyoco_render_user_page($account->uid), 
      '#attributes' => array('class' => array('icon-heart')
    ),
  );
}


/**
 * Implements HOOK_user_login.
 */
function soyoco_user_login(&$edit, $account) {
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset') {
    $_GET['destination'] = 'user';
  }
  if (user_access('view administration menu')) {
    $edit['redirect'] = 'admin/dashboard';
  }
}


